import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()

DIRECT_URL = os.getenv("DIRECT_URL")

def create_orders_schema():
    if not DIRECT_URL:
        print("ERROR: DIRECT_URL not found in env.")
        return
        
    print("Connecting to Supabase PostgreSQL database to create orders table...")
    try:
        conn = psycopg2.connect(DIRECT_URL)
        cursor = conn.cursor()
        
        # 1. Create orders table
        print("Creating 'orders' table...")
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS orders (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                pharmacy_name TEXT NOT NULL,
                drug_license TEXT NOT NULL,
                phone TEXT NOT NULL,
                address TEXT NOT NULL,
                city TEXT NOT NULL,
                state TEXT NOT NULL,
                zip TEXT NOT NULL,
                payment_method TEXT NOT NULL,
                payment_status TEXT NOT NULL DEFAULT 'PENDING',
                delivery_status TEXT NOT NULL DEFAULT 'PENDING',
                total_amount NUMERIC(12, 2) NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
            );
        """)
        
        # 2. Create order_items table
        print("Creating 'order_items' table...")
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS order_items (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
                medicine_id BIGINT REFERENCES medicines(id) ON DELETE CASCADE NOT NULL,
                quantity INTEGER NOT NULL,
                price NUMERIC(10, 2) NOT NULL
            );
        """)
        
        # 3. Create indexes
        print("Creating order index keys...")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_orders_delivery ON orders(delivery_status);")
        
        conn.commit()
        cursor.close()
        conn.close()
        print("Orders tables created successfully!")
        
    except Exception as e:
        print(f"ERROR: Failed to configure orders schema: {e}")

if __name__ == "__main__":
    create_orders_schema()
