import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()

DIRECT_URL = os.getenv("DIRECT_URL")

def setup_db():
    if not DIRECT_URL:
        print("ERROR: DIRECT_URL not found in .env file.")
        return
        
    print("Connecting to Supabase PostgreSQL database...")
    try:
        conn = psycopg2.connect(DIRECT_URL)
        cursor = conn.cursor()
        
        # 1. Create salts table
        print("Creating 'salts' table...")
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS salts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT UNIQUE NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
            );
        """)
        
        # 2. Create medicines table
        print("Creating 'medicines' table...")
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS medicines (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                salt_id BIGINT REFERENCES salts(id) ON DELETE CASCADE NOT NULL,
                name TEXT UNIQUE NOT NULL,
                url TEXT,
                image_url TEXT,
                composition TEXT,
                formulation TEXT,
                status TEXT,
                description TEXT,
                side_effects TEXT,
                dosage TEXT,
                price NUMERIC(10, 2) NOT NULL DEFAULT 9.99,
                stock INTEGER NOT NULL DEFAULT 100,
                min_order_quantity INTEGER NOT NULL DEFAULT 10,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
            );
        """)
        
        # 3. Create indexes
        print("Creating search indexes...")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_medicines_name ON medicines(name);")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_salts_name ON salts(name);")
        
        conn.commit()
        cursor.close()
        conn.close()
        print("Database schema created successfully!")
        
    except Exception as e:
        print(f"ERROR: Failed to set up database schema: {e}")

if __name__ == "__main__":
    setup_db()
